version = 0.1
[default.deploy.parameters]
stack_name = "expo-slack-notification"
resolve_s3 = true
s3_prefix = "expo-slack-notification"
region = "us-east-1"
profile = "dipo_cli"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
